### ISSUE TITLE
FTP does not connect with Cyberduck.

### ISSUE THREAD

**Issue by HybridEidolon** [xerpi/libftpvita#11]
Cyberduck (FTP client for OSX) soft hangs in a connecting state when attempting to connect to the shell to transfer files.

**Comment by xerpi** [comment]
Can you compile FTPVita in debug mode (make debug) and paste a photo or something of the debug log?

**Comment by xdotnano** [comment]
![2016-08-27-193224](https://cloud.githubusercontent.com/assets/1760735/18107663/c8a269ec-6f00-11e6-9045-238fbfc38b02.jpg)
Same thing happens in Solid Explorer and a few other Android FTP clients.

**Comment by soywiz** [comment]
I'm checking this as I encountered this problem before. Using wireshark:

<img width="959" alt="captura de pantalla 2016-09-04 a las 13 59 10" src="https://cloud.githubusercontent.com/assets/570848/18230845/d983a7c6-72a7-11e6-9b1e-cfbee045e331.png">

It seems that it is not sending anything, just connecting and receiving that. I'm going to try to look at the source code to see if it is expecting something:
https://trac.cyberduck.io/

**Comment by soywiz** [comment]
Without testing it. I just jumped in the following sources:

https://g.iterate.ch/projects/ITERATE/repos/cyberduck/browse/ftp/src/main/java/ch/cyberduck/core/ftp/FTPClient.java

That uses apache-commons-net:
https://github.com/apache/commons-net/blob/trunk/src/main/java/org/apache/commons/net/ftp/FTPSClient.java
https://github.com/apache/commons-net/blob/trunk/src/main/java/org/apache/commons/net/ftp/FTPClient.java
https://github.com/apache/commons-net/blob/trunk/src/main/java/org/apache/commons/net/ftp/FTP.java

And ended here:
https://github.com/apache/commons-net/blob/trunk/src/main/java/org/apache/commons/net/SocketClient.java#L61

I have find out that it sends a \n instead of \r\n as it seems to be the EOL specified in the RFC, maybe could be because of that?

I will compile a version with that change and try, and if that's the case I will create a PR.

**Comment by soywiz** [comment]
Hang problem fixes, but still:

<img width="1014" alt="captura de pantalla 2016-09-04 a las 14 42 23" src="https://cloud.githubusercontent.com/assets/570848/18231054/d238192e-72ad-11e6-8c2b-116f886cda2c.png">

**Comment by xerpi** [comment]
Yeah that "LIST -a" looks very odd, it looks like it's using Unix ls tool parameters.
libftpvita doesn't support it and it will try to list a directory named "-a", which doesn't exist.
Try disabling extended features in your FTP client.
